config/routes.rb
RailsApp::Application.routes.draw do

  resources :public, only: [:home, :test] do
    collection do
      get 'home'
      get 'test'
    end
  end

  resources :achievements do
    resources :comments
  end

  resources :challenges do
    resources :comments, only: [:index, :create]
  end

  resources :comments, only: [:index, :show, :new]

  devise_for :users, controllers: {
    omniauth_callbacks: "omniauth_callbacks",
    registrations: "registrations"
  }

  resources :users

  get 'signup', to: 'users#new', as: 'signup'

  root :to => 'public#home'

  mount JasmineRails::Engine => "/specs" if defined?(JasmineRails)
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	attr_accessible :body, :commentable_id, :commentable_type
	belongs_to :commentable, polymorphic: true
  
	validates_presence_of :body
	validates_length_of :body, :within => 10..2000  
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_filter :find_commentable

  respond_to :json

  # GET /commentable/:id/comments.json
  def index
    respond_to do |format|
      format.html { render :layout => false } # index.html.haml
      format.json { render json: @commentable.comments }
    end
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @comment }
    end
  end

  # new_post_comment GET /posts/:post_id/comments/new
  # new_post_comment GET /posts/:post_id/comments/new.js
  def new
    @comment = Comment.new

    respond_to do |format|
      format.html { render :layout => false } # new.html.erb
      format.js #new.js.erb
    end
  end

  # GET /comments/1/edit
  def edit
    # do nothing
  end 
  
  # POST /commentable/:id/comments.json
  def create
    @comment = @commentable.comments.build(params[:comment])    
    if @comment.save
      respond_with @comment 
    else
      respond_with :nothing => true
    end
  end

  # PUT /comments/1
  # PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update_attributes(params[:comment])
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy

    respond_to do |format|
      format.json { head :no_content }
    end
  end

  def find_commentable
    @commentable = nil
    params.each do |name,value|
      if name =~ /(.+)_id$/
        @commentable = $1.classify.constantize.find(value)
        return
      end
    end
  end

end

app/views/comments/_comment.html.erb
<blockquote>
		<strong>Posted <%= time_ago_in_words(comment.created_at) %>ago</strong><br/>
		<%= h(comment.body)%>
</blockquote>

app/views/comments/_form.html.erb
<%= form_for([post,comment], :html => { :class => "form-horizontal well" }) do |f| %>
	<% if comment.errors.any? %>
		<div id="error_explanation" class="alert alert-error">
			<h5><strong><%= pluralize(comment.errors.count, "error") %></strong> prohibited this comment from being saved:</h5>

			<ul>
				<% comment.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
				<% end %>
			</ul>
			<button type="button" class="close" data-dismiss="alert">&times;</button>
		</div>
	<% end %>

	<fieldset>
		<legend>comment Details</legend>
		<div class="control-group">
			<%= f.label :title, :class => "control-label" %>
			<div class="controls">
				<%= f.text_field :title, :class => "input-xlarge", :rows => 4 %>
			</div>
		</div>
		<div class="control-group">
			<%= f.label :body, :class => "control-label" %>
			<div class="controls">
				<%= f.text_area :body, :class => "input-xlarge", :rows => 4 %>
			</div>
		</div>
		<div class="actions">
			<%= f.submit "Save comment", id: "save_comment", :class => "btn btn-info btn-small" %>
			<%= link_to "Cancel", posts_path, id: "cancel_comment", :class => "btn btn-primary btn-small" %>
		</div>		  
	</fieldset>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>


<%= render :partial => 'form', :locals => { :post => @post, :comment => @comment } %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.haml
%ul.comments
  %li{ :id        => "comment-{{ comment.id }}",
    "ng-repeat"   => "comment in comments",
    "commentable" => true,
    "actionable" => true }
    %blockquote 
      = "{{ comment.body }}"
      %p.actions
    .children

app/views/comments/new.html.haml
%form{ "ng-submit" => "saveComment(commentableModel.id,newComment)" }
  %blockquote
    %textarea.span3{ :rows => 4, "ng-model" => "newComment.body"  }= "Leave a message..."
    %input.btn.btn-warning{ :type => :submit, :value => "Reply" }

app/views/comments/new.js.erb
<% id = @post.id %>
$('#post_<%= id %> #new_comment').addClass('disabled')
$('#post_<%= id %> #new_comment').click(function () {return false;});
$('#post_<%= id %> #new_comment_form').hide().append('<%= j render("form") %>').slideDown()
$('#post_<%= id %> #cancel_comment').click(function(event) {
	event.preventDefault()
	$('#post_<%= id %> #new_comment').removeClass('disabled')
	$('#post_<%= id %> #new_comment').unbind('click')
	$('#post_<%= id %> #new_comment_form').slideUp(400, function() {
		$(this).empty()
		$(this).show()
	})	
});

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Post:</strong>
  <%= @comment.post_id %>
</p>

<p>
  <strong>Body:</strong>
  <%= @comment.body %>
</p>


<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>