config/routes.rb
RailsApp::Application.routes.draw do

  resources :public, only: [:home, :test] do
    collection do
      get 'home'
      get 'test'
    end
  end

  resources :achievements do
    resources :comments
  end

  resources :challenges do
    resources :comments, only: [:index, :create]
  end

  resources :comments, only: [:index, :show, :new]

  devise_for :users, controllers: {
    omniauth_callbacks: "omniauth_callbacks",
    registrations: "registrations"
  }

  resources :users

  get 'signup', to: 'users#new', as: 'signup'

  root :to => 'public#home'

  mount JasmineRails::Engine => "/specs" if defined?(JasmineRails)
end

app/models/user.rb
class User < ActiveRecord::Base
	# Include default devise modules. Others available are:
	# :token_authenticatable, :confirmable,
	# :lockable, :timeoutable
	devise :database_authenticatable, :registerable, :omniauthable,
	     :recoverable, :rememberable, :trackable, :validatable

	# Setup accessible (or protected) attributes for your model
	attr_accessible :username, :first_name, :last_name, :email, :password, 
		:password_confirmation, :remember_me

	def self.from_omniauth(auth)
	  where(auth.slice(:provider, :uid)).first_or_create do |user|
	    user.provider = auth.provider
	    user.uid = auth.uid
	    user.username = auth.info.nickname
		user.email = auth.info.email
	  end
	end

	def self.new_with_session(params, session)
	  if session["devise.user_attributes"]
	    new(session["devise.user_attributes"], without_protection: true) do |user|
	      user.attributes = params
	      user.valid?
	    end
	  else
	    super
	  end
	end

	def password_required?
	  super && provider.blank?
	end

	def update_with_password(params, *options)
	  if encrypted_password.blank?
	    update_attributes(params, *options)
	  else
	    super
	  end
	end
end

app/controllers/admin/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  
  def index
    #@users = User.all
    @users = User.search(params[:search])

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
    render layout: "details"
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  # GET /users/new
  def new
    @user = User.new
  end
  
  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])
    if @user.save
      UserMailer.delay(:queue => 'notifications').register_confirmation(@user)
      flash[:notice] = "Congratulations, you are a new member. You will receive an email to activate your member login."
    else
      render :new
    end
  end
end

app/views/admin/users/_form.html.erb
<%= form_for(@user, :html => { :class => "form-horizontal well" }) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation" class="alert alert-error">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

	<fieldset>
		<legend>user Details</legend>
				  <div class="control-group">
		    <%= f.label :first_name, :class => "control-label" %>
		    <div class="controls">
		    <%= f.text_field :first_name, :class => "input-xlarge" %>
		    </div>
		  </div>
				  <div class="control-group">
		    <%= f.label :last_name, :class => "control-label" %>
		    <div class="controls">
		    <%= f.text_field :last_name, :class => "input-xlarge" %>
		    </div>
		  </div>
				  <div class="control-group">
		    <%= f.label :password, :class => "control-label" %>
		    <div class="controls">
		    <%= f.text_field :password, :class => "input-xlarge" %>
		    </div>
		  </div>
				  <div class="control-group">
		    <%= f.label :email, :class => "control-label" %>
		    <div class="controls">
		    <%= f.text_field :email, :class => "input-xlarge" %>
		    </div>
		  </div>
				  <div class="control-group">
		    <%= f.label :login, :class => "control-label" %>
		    <div class="controls">
		    <%= f.text_field :login, :class => "input-xlarge" %>
		    </div>
		  </div>
				  <div class="control-group">
		    <%= f.label :avatar, :class => "control-label" %>
		    <div class="controls">
		    <%= f.text_field :avatar, :class => "input-xlarge" %>
		    </div>
		  </div>
			<div class="actions">
				<%= f.submit :class => "btn btn-info" %>
				<%= link_to 'Back', users_path, :class => "btn" %>
			</div>
	</fieldset>
<% end %>

app/views/admin/users/edit.html.erb
<h1>Editing user</h1>

<% content_for :button_group do %>
	<%= link_to 'Show', @user %> |
	<%= link_to 'Back', users_path %>
<% end %>

<%= render 'form', :layout => 'layouts/details' %>

app/views/admin/users/index.html.erb
<legend>Listing users</legend>

<%= form_tag(users_path, :class => "well form-search", :method => "get") do %>
	<p>
		<%= text_field_tag :search, params[:search] %>
		<%= submit_tag "Search", :class => "btn", :name => nil %>
	</p>
<% end %>

<table class="table table-bordered table-striped table-hover">
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Password</th>
      <th>Email</th>
      <th>Login</th>
      <th>Avatar</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
    <tr>
      <td><%= user.first_name %></td>
      <td><%= user.last_name %></td>
      <td><%= user.password %></td>
      <td><%= user.email %></td>
      <td><%= user.login %></td>
      <td><%= user.avatar %></td>
			<td>
		    <div class="btn-group">
			    <button class="btn dropdown-toggle" data-toggle="dropdown">
			    Action
			    <span class="caret"></span>
			    </button>
			    <ul class="dropdown-menu">
			    	<li><%= link_to 'Show', user  %></li>
			    	<li><%= link_to 'Edit', edit_user_path(user)  %></li>
			    	<li class="divider"></li>
			    	<li><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></li>
			    </ul>
		    </div>
			</td>
    </tr>
    <% end %>
  </tbody>
</table>

<div class="form-actions">
<%= link_to 'New User', new_user_path, :class => "btn btn-info" %>
</div>

app/views/admin/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/admin/users/show.html.erb
<p id="notice" class="alert alert-success"><%= notice %></p>

<p>
  <b>First name:</b>
  <%= @user.first_name %>
</p>

<p>
  <b>Last name:</b>
  <%= @user.last_name %>
</p>

<p>
  <b>Password:</b>
  <%= @user.password %>
</p>

<p>
  <b>Email:</b>
  <%= @user.email %>
</p>

<p>
  <b>Login:</b>
  <%= @user.login %>
</p>

<p>
  <b>Avatar:</b>
  <%= @user.avatar %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>